apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeouttest
spec:
  selector:
    matchLabels:
      app: timeouttest
  replicas: 1 
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: timeouttest
          image: timeouttest:latest 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 
